version: "3"
services:
  books:
    build:
      context: .
    ports:
      - "${BOOKSWAP_PORT}:${BOOKSWAP_PORT}"
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env
  db:
    image: postgres:15.0-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d books" ]
      interval: 1s
      timeout: 1s
      retries: 5
